### ISSUE TITLE
Do we need app to send best_build_id?

### ISSUE THREAD

**Issue by samselikoff** [tedconf/front_end_builds#32]
When the user activates a build from the UI, the best_build may change. Do we really need to ask Rails to update the best_build_id? Why don't we just have the logic for what the best_build is in the frontend?

The logic for `find_best` is complex in the backend, because it takes lots of params. The only one we need for the frontend is the best at the default url, which (correct me if I'm wrong) is just the latest active master. Correct?

In this case, we can drop `best_build_id` and that will make keeping the UI in sync with the best_build as the user is clicking around much easier.

Thoughts?

**Comment by ryanto** [comment]
Makes sense.

``find_best`` is really used to find the best build based on your params (master/branch/sha smoke test/whatever). It's not really used for promotion/rollback purposes.

I didn't consider the UI/sync issues with maintaining best_id (since its not really an updatable thing). Sounds like a pain.

:+1: For having the front end have its own logic, and yes it's just ``master+active+latest created_at``.

**Comment by samselikoff** [comment]
Ok great so we need

- [ ] to remove best_build_id from an app's serialized json in the backend and
- [ ] to add the logic to the frontend
