### ISSUE TITLE
public assets not getting merged

### ISSUE THREAD

**Issue by samselikoff** [tedconf/front_end_builds#46]
gem works with dummy in `spec` but not currently with an actual external app. Public folder isn't getting merged.

This is why it didn't work yesterday, I'm looking into it.

/cc @ryanto

**Comment by ryanto** [comment]
So what's happening is by default Rails doesn't serve static assets in production mode (``config.serve_static_files``). The idea here is that these are better/faster served from your web server compared to having the request served from the Rails app.

We should probably go back to using the asset pipeline because it is probably the most standard and straight forward way of doing this. The cons are: User will need to make sure assets are built during deploy phase and slower backend deploy when admin area updates. 

I wonder if there is a way we can have sprockets not minify our assets (since they're already minified by ember-cli). That should make the deploy go quickly and allow use to use the asset pipeline.

**Comment by samselikoff** [comment]
I don't think that's it because it doesn't even work in development.

**Comment by ryanto** [comment]
Ah my mistake, thought it was ok in dev mode. Let me mess with the demo app to see if I can track this down.

**Comment by johnmcdowall** [comment]
I ran into this too yesterday, but specifying a `git` path for the Gem in the Gemfile to this repo fixed the problem. Seems to indicate something about the Gem packaging might not be correct. 

Is it possibly because you haven't specified the `admin` directory here:

https://github.com/tedconf/front_end_builds/blob/master/front_end_builds.gemspec#L17

So the contents of the admin folder aren't actually getting packaged into the Gem?

**Comment by ryanto** [comment]
@johnmcdowall Great find!!! We had to add `public/**/*` to the gem files since that's where the built assets are. Thanks so much.

I just tested a deploy using version ``0.0.23`` and everything looks to be working.

**Comment by ryanto** [comment]
https://github.com/tedconf/front_end_builds/commit/bda48dcd51776d56f86181367f5f42d602d9728c

**Comment by johnmcdowall** [comment]
@ryanto sweet!

**Comment by samselikoff** [comment]
excellent work, thanks @johnmcdowall !
