### ISSUE TITLE
Update for Rails 5

### ISSUE THREAD

**Issue by nselikoff** [tedconf/front_end_builds#79]
Running through the install instructions with a fresh install of Rails 5.0.2, the app gets stuck when POSTing to create a new frontend:

```
Processing by FrontEndBuilds::AppsController#create as JSON
  Parameters: {"app"=>{"name"=>"my-app", "api_key"=>nil, "location"=>nil, "require_manual_activation"=>false, "live_build_id"=>nil}}
Completed 500 Internal Server Error in 44ms (ActiveRecord: 0.0ms)



NoMethodError (undefined method `app_create_params_rails_5' for #<FrontEndBuilds::AppsController:0x007fb8fd9106f0>
Did you mean?  app_create_params_rails_4
               app_create_params_rails_3
               app_update_params_rails_4
               app_update_params_rails_3):
```

**Comment by samselikoff** [comment]
These methods are so FEB works with different rails versions. Looks like we haven't added new ones since Rails 5 released.

- [app create](https://github.com/tedconf/front_end_builds/blob/master/app/controllers/front_end_builds/apps_controller.rb#L80)
- [app update](https://github.com/tedconf/front_end_builds/blob/master/app/controllers/front_end_builds/apps_controller.rb#L94)
- [pubkey create](https://github.com/tedconf/front_end_builds/blob/0ff38e4e5660a0496e2bde364b8fdbbf0b35a72c/app/controllers/front_end_builds/pubkeys_controller.rb#L43)
- [build create](https://github.com/tedconf/front_end_builds/blob/0ff38e4e5660a0496e2bde364b8fdbbf0b35a72c/app/controllers/front_end_builds/builds_controller.rb#L71)

Dirty solution would be to copy those 4 and make `rails_5` methods. (The params API hasn't changed from Rails 4 to 5).

Clean solution would be to update [`use_params`](https://github.com/tedconf/front_end_builds/blob/0ff38e4e5660a0496e2bde364b8fdbbf0b35a72c/app/controllers/front_end_builds/application_controller.rb#L4) method to first try the version-specific version of the method and then fall back to a default. This would mean changing the `_rails_4` versions of the above methods to something like `app_create_params_rails_default`

**Comment by samselikoff** [comment]
Would love some help if anyone has time for this

**Comment by nickcoyne** [comment]
I think this PR aimed to address this? https://github.com/tedconf/front_end_builds/pull/76

**Comment by jhirbour** [comment]
Closed in https://github.com/tedconf/front_end_builds/pull/76
